spring.application.name=note
spring.datasource.url=jdbc:postgresql://localhost:5432/notes_db
spring.datasource.username=postgres
spring.datasource.password=1245
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Now every SQL query will appear in the console.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#jwt secret  key
security.jwt.secret-key=vTJqqFkr/TInD12LeJP5ZhkmcTxagrfjtArYTAxQFm0=
# 1h in millisecond
security.jwt.expiration-time=3600000
