CREATE TABLE IF NOT EXISTS notedb (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    note_topic VARCHAR(255),
    note_content TEXT,
    note_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    note_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);